'use client'

import { useEffect, useState } from 'react'
import { createBrowserClient } from '@supabase/ssr'

// ── Types ─────────────────────────────────────────────────────────────────────

interface AuditChange {
  id: string
  severity: string | null
  summary: string | null
  detected_at: string
  review_status: string
  chain_sequence: number | null
  hash: string | null
  sources: { name: string } | null
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' })
}

// ── Component ─────────────────────────────────────────────────────────────────

export default function AuditExportPage() {
  const [changes, setChanges] = useState<AuditChange[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const supabase = createBrowserClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!
    )
    supabase
      .from('changes')
      .select('id, severity, summary, detected_at, review_status, chain_sequence, hash, sources(name)')
      .not('chain_sequence', 'is', null)
      .order('chain_sequence', { ascending: false })
      .limit(500)
      .then(({ data }) => {
        setChanges((data ?? []) as unknown as AuditChange[])
        setLoading(false)
      })
  }, [])

  useEffect(() => {
    if (!loading && changes.length > 0) {
      setTimeout(() => window.print(), 300)
    }
  }, [loading, changes.length])

  const now = new Date().toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' })

  // Force white background — this is a print document, always light regardless of OS theme
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-4xl mx-auto px-8 py-8 font-sans text-sm text-gray-900">
        {/* Letterhead */}
        <div className="flex items-center justify-between border-b border-gray-200 pb-4 mb-6">
          <div>
            <img src="/cedar-logo-light.svg" alt="Cedar" className="h-5 w-auto mb-1" />
            <p className="text-xs text-gray-500">Florida Regulatory Intelligence</p>
          </div>
          <div className="text-right text-xs text-gray-500">
            <h1 className="font-semibold text-gray-700 text-sm">Audit Trail Export</h1>
            <p>Generated {now}</p>
          </div>
        </div>

        {loading ? (
          <p className="text-gray-400 italic">Loading audit records…</p>
        ) : (
          <>
            <p className="text-xs text-gray-500 mb-4">
              {changes.length} record{changes.length !== 1 ? 's' : ''} · Hash chain ordered descending by sequence number
            </p>

            <table className="w-full border-collapse text-xs">
              <thead>
                <tr className="border-b-2 border-gray-200">
                  <th className="text-left py-2 pr-3 font-semibold text-gray-600 w-12">Seq</th>
                  <th className="text-left py-2 pr-3 font-semibold text-gray-600 w-32">Source</th>
                  <th className="text-left py-2 pr-3 font-semibold text-gray-600 w-20">Severity</th>
                  <th className="text-left py-2 pr-3 font-semibold text-gray-600">Summary</th>
                  <th className="text-left py-2 pr-3 font-semibold text-gray-600 w-32">Detected</th>
                  <th className="text-left py-2 font-semibold text-gray-600 w-28">Hash</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {changes.map((c) => (
                  <tr key={c.id}>
                    <td className="py-2 pr-3 font-mono text-gray-400">#{c.chain_sequence}</td>
                    <td className="py-2 pr-3 text-gray-700">{c.sources?.name ?? '—'}</td>
                    <td className="py-2 pr-3 text-gray-700 capitalize">{c.severity ?? '—'}</td>
                    <td className="py-2 pr-3 text-gray-700 max-w-xs">
                      {c.summary ? (c.summary.length > 120 ? c.summary.slice(0, 120) + '…' : c.summary) : '—'}
                    </td>
                    <td className="py-2 pr-3 text-gray-500 whitespace-nowrap"><time dateTime={new Date(c.detected_at).toISOString()}>{formatDate(c.detected_at)}</time></td>
                    <td className="py-2 font-mono text-gray-400">{c.hash ? c.hash.slice(0, 12) + '…' : '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            {/* Disclaimer */}
            <div className="mt-8 pt-4 border-t border-gray-200">
              <p className="text-xs text-gray-500">
                <strong>Disclaimer:</strong> This audit trail was generated by Cedar, an AI-powered regulatory intelligence platform.
                The hash chain provides tamper-evidence for detected changes but does not constitute legal advice.
                Each change record is identified by a SHA-256 content hash. Consult a licensed attorney before acting on any regulatory change.
              </p>
              <p className="text-xs text-gray-400 mt-1">Cedar — cedar-beta.vercel.app</p>
            </div>
          </>
        )}
      </div>
    </div>
  )
}
