// Module 8: Email delivery via Resend
// Sends regulatory change alert emails to practice owners.
//
// Template features:
//   - Severity-weight header (critical = red, informational = blue)
//   - AI summary section
//   - Diff preview: up to 12 unified-diff lines shown inline
//   - "View Full Details" CTA links to the dashboard change page
//   - "Mark as Reviewed" button writes a practice_acknowledgment via API route
//   - Plain-text fallback with summary + truncated diff
//   - Mandatory AI disclaimer footer on every email

import { Resend } from 'resend'
import { getEnv } from '../env'
import type { DiffBlock } from '../changes/diff'

// ── Types ─────────────────────────────────────────────────────────────────────

export interface SendChangeAlertParams {
  to: string
  practiceName: string
  changeSummary: string
  severity: string
  sourceName: string
  sourceUrl: string
  changeId: string
  /** Structured diff blocks from changes.normalized_diff — used for inline preview */
  normalizedDiff?: DiffBlock[] | null
  /** Effective date of the change if known (YYYY-MM-DD) */
  effectiveDate?: string | null
}

export interface SendChangeAlertResult {
  sent: boolean
  reason?: string
  messageId?: string
}

// ── Constants ─────────────────────────────────────────────────────────────────

const DISCLAIMER =
  'This summary was generated by AI and has not been reviewed by a licensed attorney. ' +
  'This is not legal advice. For decisions specific to your practice, consult your legal counsel.'

type SeverityConfig = { color: string; bg: string; label: string; urgency: string }

const SEVERITY_CONFIG: Record<string, SeverityConfig> = {
  critical:      { color: '#dc2626', bg: '#fef2f2', label: 'Critical',      urgency: 'Immediate action may be required.' },
  high:          { color: '#ea580c', bg: '#fff7ed', label: 'High',           urgency: 'Review within 24 hours recommended.' },
  medium:        { color: '#d97706', bg: '#fffbeb', label: 'Medium',         urgency: 'Review at your earliest convenience.' },
  low:           { color: '#65a30d', bg: '#f7fee7', label: 'Low',            urgency: 'Informational — no immediate action required.' },
  informational: { color: '#0284c7', bg: '#f0f9ff', label: 'Informational',  urgency: 'No action required.' },
}

const DEFAULT_SEVERITY: SeverityConfig = { color: '#6b7280', bg: '#f9fafb', label: 'Update', urgency: '' }

// Max diff lines shown in preview — keeps emails scannable
const DIFF_PREVIEW_MAX_LINES = 12

// ── Main function ─────────────────────────────────────────────────────────────

/**
 * Send a regulatory change alert email via Resend.
 * Returns { sent: false, reason } when RESEND_API_KEY is not configured.
 */
export async function sendChangeAlert(
  params: SendChangeAlertParams
): Promise<SendChangeAlertResult> {
  const env = getEnv()
  if (!env.RESEND_API_KEY) {
    return { sent: false, reason: 'RESEND_API_KEY not configured' }
  }

  const resend = new Resend(env.RESEND_API_KEY)
  const appUrl = env.NEXT_PUBLIC_APP_URL ?? 'https://cedar-beta.vercel.app'
  const { to, practiceName, changeSummary, severity, sourceName, sourceUrl, changeId, normalizedDiff, effectiveDate } = params
  const sev = SEVERITY_CONFIG[severity.toLowerCase()] ?? DEFAULT_SEVERITY

  const detailsUrl     = `${appUrl}/changes/${changeId}`
  const acknowledgeUrl = `${appUrl}/api/changes/${changeId}/acknowledge`

  const html = buildHtml({ practiceName, changeSummary, sev, sourceName, sourceUrl, normalizedDiff, effectiveDate, detailsUrl, acknowledgeUrl })
  const text = buildText({ practiceName, changeSummary, sev, sourceName, sourceUrl, normalizedDiff, effectiveDate, detailsUrl })

  const { data, error } = await resend.emails.send({
    from: 'Cedar Intelligence <alerts@cedarintelligence.com>',
    to,
    subject: `[${sev.label}] Regulatory Change — ${sourceName}`,
    html,
    text,
  })

  if (error) {
    throw new Error(`Resend error: ${error.message}`)
  }

  return { sent: true, messageId: data?.id }
}

// ── HTML builder ──────────────────────────────────────────────────────────────

interface TemplateParams {
  practiceName: string
  changeSummary: string
  sev: SeverityConfig
  sourceName: string
  sourceUrl: string
  normalizedDiff?: DiffBlock[] | null
  effectiveDate?: string | null
  detailsUrl: string
  acknowledgeUrl?: string
}

function buildHtml(p: TemplateParams): string {
  const diffHtml = p.normalizedDiff?.length ? buildDiffPreviewHtml(p.normalizedDiff) : ''
  const effectiveLine = p.effectiveDate
    ? `<p style="margin:0 0 20px;font-size:13px;color:#6b7280;"><strong style="color:#374151;">Effective date:</strong> ${p.effectiveDate}</p>`
    : ''

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Regulatory Alert — ${p.sev.label}</title>
</head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f3f4f6;margin:0;padding:32px 16px;">
<div style="max-width:600px;margin:0 auto;">

  <p style="margin:0 0 16px;font-size:11px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#9ca3af;">Cedar Regulatory Intelligence</p>

  <div style="background:#fff;border-radius:10px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,0.08);">

    <!-- Severity banner -->
    <div style="background:${p.sev.color};padding:16px 28px;">
      <span style="display:inline-block;background:rgba(255,255,255,0.25);color:#fff;font-size:11px;font-weight:700;padding:3px 10px;border-radius:99px;text-transform:uppercase;letter-spacing:0.08em;margin-right:10px;">${p.sev.label}</span>
      <span style="color:rgba(255,255,255,0.9);font-size:13px;">${p.sev.urgency}</span>
    </div>

    <!-- Content -->
    <div style="padding:28px 32px;">

      <p style="margin:0 0 4px;font-size:14px;font-weight:600;color:#374151;">Hi ${e(p.practiceName)},</p>
      <p style="margin:0 0 24px;font-size:14px;color:#6b7280;">A regulatory change relevant to your practice has been detected.</p>

      <!-- Source card -->
      <div style="background:${p.sev.bg};border-left:3px solid ${p.sev.color};border-radius:0 6px 6px 0;padding:10px 14px;margin-bottom:24px;">
        <p style="margin:0 0 2px;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;color:${p.sev.color};">Source</p>
        <a href="${p.sourceUrl}" style="font-size:14px;font-weight:600;color:#111827;text-decoration:none;">${e(p.sourceName)}</a>
      </div>

      ${effectiveLine}

      <!-- Summary -->
      <h2 style="margin:0 0 10px;font-size:15px;font-weight:600;color:#111827;">AI Summary</h2>
      <p style="margin:0 0 28px;font-size:15px;line-height:1.65;color:#374151;">${e(p.changeSummary)}</p>

      ${diffHtml}

      <!-- CTAs -->
      <div>
        <a href="${p.detailsUrl}" style="display:inline-block;background:#111827;color:#fff;font-size:14px;font-weight:600;padding:11px 22px;border-radius:6px;text-decoration:none;margin-right:10px;">View Full Details →</a>
        ${p.acknowledgeUrl ? `<a href="${p.acknowledgeUrl}" style="display:inline-block;background:#fff;color:#374151;font-size:14px;font-weight:500;padding:11px 22px;border-radius:6px;text-decoration:none;border:1px solid #d1d5db;">Mark as Reviewed ✓</a>` : ''}
      </div>

    </div>

    <!-- Disclaimer -->
    <div style="padding:20px 32px;background:#f9fafb;border-top:1px solid #e5e7eb;">
      <p style="margin:0;font-size:11px;line-height:1.6;color:#9ca3af;">${DISCLAIMER}</p>
    </div>

  </div>

  <p style="margin:18px 0 0;text-align:center;font-size:11px;color:#d1d5db;">
    Cedar Intelligence &middot; <a href="${p.detailsUrl}" style="color:#9ca3af;text-decoration:none;">Manage Preferences</a>
  </p>

</div>
</body>
</html>`
}

// ── Diff preview (HTML) ───────────────────────────────────────────────────────

function buildDiffPreviewHtml(blocks: DiffBlock[]): string {
  const changed = blocks.filter(b => b.type !== 'unchanged')
  if (changed.length === 0) return ''

  const preview = changed.slice(0, DIFF_PREVIEW_MAX_LINES)
  const overflow = changed.length - preview.length

  const rows = preview.map(block => {
    const content = e(block.content.trim())
    if (!content) return ''
    if (block.type === 'added') {
      return `<div style="background:#f0fdf4;border-left:3px solid #16a34a;padding:5px 10px;margin:2px 0;font-size:12px;font-family:monospace;color:#15803d;border-radius:0 2px 2px 0;">+ ${content}</div>`
    }
    return `<div style="background:#fef2f2;border-left:3px solid #dc2626;padding:5px 10px;margin:2px 0;font-size:12px;font-family:monospace;color:#991b1b;text-decoration:line-through;border-radius:0 2px 2px 0;">− ${content}</div>`
  }).filter(Boolean).join('\n')

  if (!rows) return ''

  return `<h2 style="margin:0 0 10px;font-size:15px;font-weight:600;color:#111827;">What Changed</h2>
<div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:6px;padding:12px;margin-bottom:28px;">
  ${rows}
  ${overflow > 0 ? `<p style="margin:8px 0 0;font-size:11px;color:#9ca3af;">+${overflow} more block${overflow > 1 ? 's' : ''} — view full details for complete diff</p>` : ''}
</div>`
}

// ── Plain-text builder ────────────────────────────────────────────────────────

function buildText(p: Omit<TemplateParams, 'acknowledgeUrl'>): string {
  const lines: string[] = [
    `CEDAR REGULATORY ALERT — ${p.sev.label.toUpperCase()}`,
    p.sev.urgency,
    '',
    `Hi ${p.practiceName},`,
    'A regulatory change relevant to your practice has been detected.',
    '',
    `SOURCE: ${p.sourceName}`,
    `URL:    ${p.sourceUrl}`,
    ...(p.effectiveDate ? [`EFFECTIVE DATE: ${p.effectiveDate}`] : []),
    '',
    'AI SUMMARY',
    '──────────',
    p.changeSummary,
    '',
  ]

  if (p.normalizedDiff?.length) {
    const changed = p.normalizedDiff
      .filter(b => b.type !== 'unchanged')
      .slice(0, DIFF_PREVIEW_MAX_LINES)
      .map(b => `${b.type === 'added' ? '+' : '-'} ${b.content.trim()}`)
    if (changed.length > 0) {
      lines.push('WHAT CHANGED (preview)', '──────────────────────', ...changed, '')
    }
  }

  lines.push(`View details: ${p.detailsUrl}`, '', '---', DISCLAIMER)
  return lines.join('\n')
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/** HTML-escape a string */
function e(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;')
}
