// Module 8: Email delivery via Resend
// Sends regulatory change alert emails to practice owners

import { Resend } from 'resend'
import { getEnv } from '../env'

export interface SendChangeAlertParams {
  to: string
  practiceName: string
  changeSummary: string
  severity: string
  sourceName: string
  sourceUrl: string
  changeId: string
}

export interface SendChangeAlertResult {
  sent: boolean
  reason?: string
  messageId?: string
}

const SEVERITY_COLOR: Record<string, string> = {
  critical: '#dc2626',
  high: '#ea580c',
  medium: '#d97706',
  low: '#65a30d',
  informational: '#0284c7',
}

const DISCLAIMER =
  'This summary was generated by AI and has not been reviewed by a licensed attorney. ' +
  'This is not legal advice. For decisions specific to your practice, consult your legal counsel.'

/**
 * Send a regulatory change alert email via Resend.
 * Returns { sent: false, reason } when RESEND_API_KEY is not configured
 * so callers can log the skip without crashing the pipeline.
 */
export async function sendChangeAlert(
  params: SendChangeAlertParams
): Promise<SendChangeAlertResult> {
  const resendKey = getEnv().RESEND_API_KEY
  if (!resendKey) {
    return { sent: false, reason: 'RESEND_API_KEY not configured' }
  }

  const resend = new Resend(resendKey)
  const { to, practiceName, changeSummary, severity, sourceName, sourceUrl, changeId } = params

  const severityColor = SEVERITY_COLOR[severity.toLowerCase()] ?? '#6b7280'
  const severityLabel = severity.charAt(0).toUpperCase() + severity.slice(1)

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f9fafb; margin: 0; padding: 24px;">
  <div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">

    <!-- Header -->
    <div style="background: #111827; padding: 24px 32px;">
      <p style="margin: 0; color: #9ca3af; font-size: 12px; text-transform: uppercase; letter-spacing: 0.1em;">Cedar Regulatory Intelligence</p>
      <h1 style="margin: 8px 0 0; color: white; font-size: 20px; font-weight: 600;">Regulatory Change Detected</h1>
    </div>

    <!-- Severity badge -->
    <div style="padding: 16px 32px; background: #f9fafb; border-bottom: 1px solid #e5e7eb;">
      <span style="display: inline-block; background: ${severityColor}; color: white; font-size: 12px; font-weight: 600; padding: 4px 12px; border-radius: 99px; text-transform: uppercase; letter-spacing: 0.05em;">
        ${severityLabel}
      </span>
      <span style="margin-left: 12px; color: #6b7280; font-size: 14px;">${sourceName}</span>
    </div>

    <!-- Body -->
    <div style="padding: 32px;">
      <p style="margin: 0 0 8px; color: #374151; font-size: 14px; font-weight: 600;">Hi ${practiceName},</p>
      <p style="margin: 0 0 24px; color: #6b7280; font-size: 14px;">A regulatory change relevant to your practice has been detected.</p>

      <h2 style="margin: 0 0 12px; color: #111827; font-size: 16px; font-weight: 600;">Summary</h2>
      <p style="margin: 0 0 24px; color: #374151; font-size: 15px; line-height: 1.6;">${changeSummary}</p>

      <h2 style="margin: 0 0 12px; color: #111827; font-size: 16px; font-weight: 600;">Source</h2>
      <p style="margin: 0 0 24px;">
        <a href="${sourceUrl}" style="color: #2563eb; font-size: 14px;">${sourceName}</a>
      </p>

      <a href="https://app.cedarintelligence.com/changes/${changeId}"
         style="display: inline-block; background: #111827; color: white; font-size: 14px; font-weight: 600; padding: 12px 24px; border-radius: 6px; text-decoration: none;">
        View Full Details →
      </a>
    </div>

    <!-- Disclaimer -->
    <div style="padding: 24px 32px; background: #f9fafb; border-top: 1px solid #e5e7eb;">
      <p style="margin: 0; color: #9ca3af; font-size: 12px; line-height: 1.5;">${DISCLAIMER}</p>
    </div>

  </div>
</body>
</html>
`

  const text = [
    `CEDAR REGULATORY ALERT — ${severityLabel}`,
    '',
    `Source: ${sourceName}`,
    `URL: ${sourceUrl}`,
    '',
    'SUMMARY',
    changeSummary,
    '',
    `View details: https://app.cedarintelligence.com/changes/${changeId}`,
    '',
    '---',
    DISCLAIMER,
  ].join('\n')

  const { data, error } = await resend.emails.send({
    from: 'Cedar Intelligence <alerts@cedarintelligence.com>',
    to,
    subject: `[${severityLabel}] Regulatory Change — ${sourceName}`,
    html,
    text,
  })

  if (error) {
    throw new Error(`Resend error: ${error.message}`)
  }

  return { sent: true, messageId: data?.id }
}
