import { Badge, Text } from '@radix-ui/themes'

// ── AiBadge ──────────────────────────────────────────────────────────────────
// The inline chip. Used on every AI surface at every tier (collection + detail).
// Placement: inline with section heading via <Flex align="center" gap="2">.
export function AiBadge() {
  return (
    <Badge color="gray" variant="soft" size="1">
      AI-generated
    </Badge>
  )
}

// ── AiDisclaimer ─────────────────────────────────────────────────────────────
// Inline disclaimer. Used ONLY on detail views, INSIDE the AI content card,
// below the AI-generated text. Never on collection views.
export function AiDisclaimer() {
  return (
    <Text as="p" size="1" color="gray" mt="3" className="leading-relaxed">
      This summary was generated by AI and has not been reviewed by a licensed attorney.
      This is not legal advice. For decisions specific to your practice, consult your
      legal counsel.
    </Text>
  )
}
