import { Callout } from '@radix-ui/themes'

export function LegalDisclaimer() {
  return (
    <Callout.Root mt="6" color="gray" variant="soft">
      <Callout.Icon>
        <i className="ri-scales-3-line" />
      </Callout.Icon>
      <Callout.Text>
        This summary was generated by AI and has not been reviewed by a licensed attorney.
        This is not legal advice. For decisions specific to your practice, consult your legal counsel.
      </Callout.Text>
    </Callout.Root>
  )
}
