-- Migration: 009_ontology_junction_rls.sql
-- Purpose: Originally added RLS policies for kg_entity_domains and kg_entity_jurisdictions
-- Tables affected: (none — consolidated into 008_ontology_schema.sql)
-- Special considerations: Policies and RLS enablement for these tables already exist in 008; this migration is now a no-op to avoid duplicate policies
