// ── AiBadge ──────────────────────────────────────────────────────────────────
// The inline chip. Used on every AI surface at every tier (collection + detail).
// Placement: inline with section heading via <div> with flex align center gap 2.
export function AiBadge() {
  return (
    <span className="inline-flex px-2 py-0.5 text-xs rounded">
      AI-generated
    </span>
  )
}

// ── AiDisclaimer ─────────────────────────────────────────────────────────────
// Inline disclaimer. Used ONLY on detail views, INSIDE the AI content card,
// below the AI-generated text. Never on collection views.
export function AiDisclaimer() {
  return (
    <p className="text-xs mt-3 leading-relaxed">
      This summary was generated by AI and has not been reviewed by a licensed attorney.
      This is not legal advice. For decisions specific to your practice, consult your
      legal counsel.
    </p>
  )
}
