export function LegalDisclaimer() {
  return (
    <div className="mt-6 p-4 rounded border">
      <p className="text-sm">
        This summary was generated by AI and has not been reviewed by a licensed attorney.
        This is not legal advice. For decisions specific to your practice, consult your legal counsel.
      </p>
    </div>
  )
}
